# .github/workflows/R-CMD-check.yaml
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples

name: R-CMD-check
permissions: read-all

on:
  push:
    paths:
      - "R/**"              # any R source file
      - "tests/**"          # testthat files
      - "DESCRIPTION"       # bumping version, deps, etc.
      - "NAMESPACE"         # roxygenise output
  pull_request:
    paths:
      - "R/**"
      - "tests/**"
      - "DESCRIPTION"
      - "NAMESPACE"

jobs:
  R-CMD-check:
    name: ${{ matrix.config.os }} (R ${{ matrix.config.r }})
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macos-latest,   r: "release" }
          - { os: windows-latest, r: "release" }
          - { os: ubuntu-latest,  r: "release" }
          - { os: ubuntu-latest,  r: "oldrel-1" }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: |
            c("--no-manual", "--compact-vignettes=gs+qpdf")
          error-on: "error"
